stages:

  data_collection:
    cmd: python src/data/data_collection.py
    deps:
      - src/data/data_collection.py
      - data/external/loan_data.csv
      - params.yaml
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_prep.py
    deps:
      - src/data/data_prep.py
      - data/raw
    outs:
      - data/processed

  model_building:
    cmd: python src/models/model_building.py
    deps:
      - src/models/model_building.py
      - data/processed/train_processed.csv
      - params.yaml
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/models/model_eval.py
    deps:
      - src/models/model_eval.py
      - data/processed/test_processed.csv
      - models/model.pkl
    metrics:
      - reports/metrics.json:
          cache: false